apiVersion: v1
kind: Service
metadata:
  name: analytics-api
spec:
  selector:
    app.kubernetes.io/name: analytics-api
  ports:
  - name: "5000"
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  labels:
    name: analytics-api
spec:
  replicas: 3
  selector:
    matchLabels:
      service: analytics-api
  template:
    metadata:
      labels:
        service: analytics-api
    spec:
      containers:
      - name: analytics-api
        image: arywatt/analytics:0.1.5
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: eks-db-secrets
              key: database

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eks-db-secrets
              key: admin-password

      restartPolicy: Always
