version: 0.2

phases:
  install:
    # commands:
    #       - echo "Installing Docker Buildx..."
    #       - mkdir -p ~/.docker/cli-plugins
    #       - curl -SL "https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-amd64" -o ~/.docker/cli-plugins/docker-buildx
    #       - chmod a+x ~/.docker/cli-plugins/docker-buildx
    #       - docker buildx version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- sudo yum install jq -y
      - aws --version
      - DOCKERHUB_USERNAME=$(aws secretsmanager get-secret-value --secret-id secrets/dockerhub/username --query 'SecretString' --output text )
      - DOCKERHUB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id secrets/dockerhub/password --query 'SecretString' --output text )

      # Docker login
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin


      - REPOSITORY_URI=456619976774.dkr.ecr.us-east-1.amazonaws.com/uda-analytics
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$(cat ./analytics/version)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG ./analytics


  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo $REPOSITORY_URI:$IMAGE_TAG
      #- aws ecr get-login --region us-east-1 | docker login --username AWS --password-stdin 456619976774.dkr.ecr.us-east-1.amazonaws.com
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"<container-name>","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
