apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eks-db-secrets
spec:
  provider: aws
  secretObjects:
  - secretName: eks-db-secrets  # secret created in eks
    type: Opaque
    data:
    - objectName: secrets/analytics/db  # original secret to get from aws secrets
      key: admin-password # key to access
    - objectName: secrets/analytics/db
      key: database # key to access
  # parameters:
  #   objects: |
  #       - objectName: "secrets/analytics/db"
  #         objectType: "secretsmanager"
  #         jmesPath:
  #           - path: "admin-password"
  #             objectAlias: "DB_PASSWORD"
  #           - path: "database"
  #             objectAlias: "DB_NAME"