# values.yaml

global:
  postgresql:
    auth:
      username: ""
      password: ""
      database: ""
      postgresPassword: "" # admin password
      existingSecret: "eks-db-secrets"
      secretKeys:
        adminPasswordKey: "admin-password"
        database: "database"





architecture: standalone


primary:
  persistence:
    enabled : true
    existingClaim: "postgres-pv-claim"
    mountPath: /var/lib/postgresql/data
    storageClass: "gp2"
    labels:
      selector:
        matchLabels:
          app: analytics-db


# externalSecrets:
#   postgresqlPassword:
#     awsSecretName: my-aws-secret  # Name of your secret in AWS Secrets Manager
#     awsRegion: us-east-1
#     key: postgresql-password
